# -*- coding utf-8 -*-

# Button states
STATE_AVAILABLE  = 0b000

STATE_MOVING     = 0b001
STATE_STOPPED    = 0b110

STATE_CLICKED    = 0b010
STATE_NOT_CLICKED= 0b101


TURN_DISABLED = 0b1
TURN_ENABLED = 0b1

# World states
WAITING_FORCE = 3
COMPUTING_FORCE = 4
APPLYING_FORCE = 5
